




%% *** plot fig2b
clc
close all

lw = 2.7; fs = 24; ms = '^'; msize = 12; mlw = 2;

% HTC values: planar HTC, analyticity bound, channel bound
btkk = 1.1e6;
bpc = 4e8;
bpassivity = 4e8;

near_inf = 2.5e8;
at_inf = bpc;
b_optimal2D =[14,2.40e5,1.50e7,6.75e6];
b_idealmetal = [13,2.28e5,4.66e6,2.52e6];
b_idealito = [12,9.77e4,1.49e7,4.39e6];
b_mgf2 = [11,7.94e4,6.16e6,at_inf];
b_alo = [10,4.44e4,inf,at_inf];
b_inp = [9,3.62e4,4.62e7,at_inf];
b_gaas = [8,3.02e4,3.87e7,at_inf];
b_sio2_popova = [7,2.3e4,5.56e6,at_inf];
b_sic = [6,9.32e3,2.00e7,at_inf];
b_cbn = [5,5.53e3,1.46e7,at_inf];
b_1e20si = [4,5.08e3,near_inf,at_inf];
b_al = [3,2.65e3,near_inf,2.94e7];
b_ag = [1,912,near_inf,3.3933e7];
b_au = [2,986,near_inf,3.1965e7];

% RGB for the markers
cbtkk = [0,0,0]./100;
cpc = [3, 14, 79]./256;
cpassivity = [244, 159, 28]./256;

c2D = 0.9.*[0.0195, 0.0859, 0.7500];
cidealmetal = 0.8.*[0.9961, 0.0078, 0.0078]; 
cAg = [128, 83, 65]./256; 
cAu = 1.3.*[0.0195, 0.0859, 0.7500];
cAl = 	[98, 151, 158]./256;

cInP = [240, 28, 104]./256;
cidealCdO = 0.92.*[0.8281, 0.1797, 0.1797];
cITO = [0.9414, 0.5352, 0.5352];
cGZO = [0.9961, 0.0078, 0.0078];

cSi = 1.12.*[0.6211, 0.1797, 0.8789];

cidealITO = [0, 137, 112]./256;
cInAs = [0.1055, 0.7891, 0.1055];
cGaAs = 0.93.*[171, 145, 187]./256;
cSiO2 = [0.9141, 0.4258, 0];
cSiC = [14, 56, 122]./256;
ccBN = [56, 122, 14]./256;
cAlO = 0.8.*[0,0.2578,0];
cMgF2 = [0.4102, 0.5586, 0.9531];

% number of materials for plot
nm = 14;

figcompare = figure;
set(gcf,'color','w');
axes1 = axes('Parent',figcompare);
set(gcf,'color','w');
set(axes1,'fontsize',fs')
hold(axes1,'on');
set(axes1,'FontSize',fs,'XMinorTick','off','XScale','linear','YMinorTick','on',...
    'YScale','log','position',[0.13 0.11 0.775 0.815],'TickDir','out','Box','off');
set(gcf,'position',[10,200,2900,580]);
set(gcf,'position',[10,200,2900,635]);
set(gca,'fontsize',fs)
hold on

xlabel('Material','fontsize',fs+4,'fontname','Helvetica','interpreter','tex','position',[nm/2,1400])
ylabel('HTC (Wm^{-2}K^{-1})','interpreter','tex','fontsize',fs+6)
xlim([0 nm+0.5])
ylim([6e2,7.7e8])
yticks([1e3,1e4,1e5,1e6,1e7,1e8])
yticklabels({'10^3','10^4','10^5','10^6','10^7','10^8'})
xticks(linspace(1,nm,nm))
xticklabels({''})

% *** grey patch that extends to inf
ybars = [4.62e7 bpc]; cshade = [0.8,0.8,0.8];
patch([0.01 nm+0.5 nm+0.5 0.01],[ybars(1) ybars(1),ybars(2) ybars(2)],cshade,'LineStyle','none');

% *** bound lines
plot(linspace(0,nm+0.5,(1+nm)*2),ones((1+nm)*2,1).*btkk,'linewidth',lw,'linestyle','-','color',cbtkk,'parent',axes1)
plot(linspace(0,nm+0.5,(1+nm)*2),ones((1+nm)*2,1).*bpc,'linewidth',lw,'linestyle','--','color',cpc,'parent',axes1)
plot(0.085+linspace(0,nm+0.5,(1+nm)*2),ones((1+nm)*2,1).*bpassivity,'linewidth',lw,'linestyle','--','color',cpassivity,'parent',axes1)

% *** bound data points for every material
plot(b_optimal2D(1),b_optimal2D(2),'linewidth',lw,'markersize',msize,'Marker','o','color',c2D,'markerfacecolor',c2D)
plot(b_optimal2D(1),b_optimal2D(3),'linewidth',lw,'markersize',msize,'Marker','s','color',c2D)
plot(b_optimal2D(1),b_optimal2D(4),'linewidth',lw,'markersize',msize,'Marker','^','color',c2D)

plot(b_idealmetal(1),b_idealmetal(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cidealmetal,'markerfacecolor',cidealmetal)
plot(b_idealmetal(1),b_idealmetal(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cidealmetal)
plot(b_idealmetal(1),b_idealmetal(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cidealmetal)

plot(b_idealito(1),b_idealito(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cidealITO,'markerfacecolor',cidealITO)
plot(b_idealito(1),b_idealito(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cidealITO)
plot(b_idealito(1),b_idealito(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cidealITO)

plot(b_mgf2(1),b_mgf2(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cMgF2,'markerfacecolor',cMgF2)
plot(b_mgf2(1),b_mgf2(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cMgF2)
plot(b_mgf2(1),b_mgf2(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cMgF2)

plot(b_alo(1),b_alo(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cAlO,'markerfacecolor',cAlO)
plot(b_alo(1),b_alo(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cAlO)
plot(b_alo(1),b_alo(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cAlO)

plot(b_inp(1),b_inp(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cInP,'markerfacecolor',cInP)
plot(b_inp(1),b_inp(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cInP)
plot(b_inp(1),b_inp(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cInP)

plot(b_gaas(1),b_gaas(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cGaAs,'markerfacecolor',cGaAs)
plot(b_gaas(1),b_gaas(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cGaAs)
plot(b_gaas(1),b_gaas(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cGaAs)


plot(b_sio2_popova(1),b_sio2_popova(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cSiO2,'markerfacecolor',cSiO2)
plot(b_sio2_popova(1),b_sio2_popova(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cSiO2)
plot(b_sio2_popova(1),b_sio2_popova(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cSiO2)

plot(b_sic(1),b_sic(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cSiC,'markerfacecolor',cSiC)
plot(b_sic(1),b_sic(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cSiC)
plot(b_sic(1),b_sic(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cSiC)

plot(b_cbn(1),b_cbn(2),'linewidth',lw,'markersize',msize,'Marker','o','color',ccBN,'markerfacecolor',ccBN)
plot(b_cbn(1),b_cbn(3),'linewidth',lw,'markersize',msize,'Marker','s','color',ccBN)
plot(b_cbn(1),b_cbn(4),'linewidth',lw,'markersize',msize,'Marker','^','color',ccBN)

plot(b_1e20si(1),b_1e20si(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cSi,'markerfacecolor',cSi)
plot(b_1e20si(1),b_1e20si(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cSi)
plot(b_1e20si(1),b_1e20si(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cSi)

plot(b_al(1),b_al(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cAl,'markerfacecolor',cAl)
plot(b_al(1),b_al(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cAl)
plot(b_al(1),b_al(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cAl)

plot(b_ag(1),b_ag(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cAg,'markerfacecolor',cAg)
plot(b_ag(1),b_ag(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cAg)
plot(b_ag(1),b_ag(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cAg)


plot(b_au(1),b_au(2),'linewidth',lw,'markersize',msize,'Marker','o','color',cAu,'markerfacecolor',cAu)
plot(b_au(1),b_au(3),'linewidth',lw,'markersize',msize,'Marker','s','color',cAu)
plot(b_au(1),b_au(4),'linewidth',lw,'markersize',msize,'Marker','^','color',cAu)

% *** hide ticklabels
annotation(figcompare,'rectangle',...
    [0.1249 0.87 0.005 0.1],...
    'FaceColor','w',...
    'EdgeColor','w');
% annotation(figcompare,'rectangle',...
%     [0.1249 0.84 0.005 0.01],...
%     'FaceColor','w',...
%     'EdgeColor','w');

% annotation(figcompare,'rectangle',...
%     [0.1303 0.12 0.01 0.06],...
%     'FaceColor','w',...
%     'EdgeColor','w');
hold on
% *** break axis
axes('Position',[.1169 .833 .022 .027]);
px=[1 5];
py1=[1 2];
height=1.4;
py2=py1+height;
plot(px,py1,'k','LineWidth',2);hold all;
plot(px,py2,'k','LineWidth',2);hold all;
fill([px flip(px)],[py1 flip(py2)],'w','EdgeColor','w');
px_half = [3 5]; py1_half = [1.5 2]; py2_half = py1_half+height;
fill([px_half flip(px_half)],[py1_half flip(py2_half)],cshade,'EdgeColor',cshade);
box off; axis off;

% axes('Position',[.116 .135 .022 .027]);
% px=[1 5];
% py1=[1 2];
% height=1.4;
% py2=py1+height;
% plot(px,py1,'k','LineWidth',2);hold all;
% plot(px,py2,'k','LineWidth',2);hold all;
% fill([px flip(px)],[py1 flip(py2)],'w','EdgeColor','w');
% box off; axis off;

% *** final settings
% lg = legend([p_optimal,p_epsb1,p_rod_InP,p_ideal_ITO,p_rod_Si,p_ideal_CdO,p_AlN,p_InP,p_GaAs,p_SiO2,p_graphene,p_ideal_Si,p_SiC,p_Al,p_GZO,p_CdO],'box','off');
%set(lg,'interpreter','tex','position',[0.08 0.18 0.3 0.64])
%box(axes1,'on'); axis on

% *** grey patch aftert the break axis
% ybars = [4.62e7 bpc]; cshade = [0.8,0.8,0.8];
% patch([0.01 nm nm 0.01],[ybars(1) ybars(1),ybars(2) ybars(2)],cshade,'LineStyle','none');


% *** the infinity symbol
annotation(figcompare,'textbox',...
    [0.107 0.823 0.1 0.1],...
    'Color','k',...
    'String','\infty',...
    'FontSize',fs+2,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% *** labels for bound methods
annotation(figcompare,'textbox',...
    [0.03 0.873 0.5 0.1],...
    'Color',cpc,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Channel bound → \infty',...
    'FontSize',fs+2,...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(figcompare,'textbox',...
    [0.495 0.873 0.5 0.1],...
    'Color',cpassivity,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Analyticity bound → \infty',...
    'FontSize',fs+2,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% *** manual legend
plot(11.4,1.4e3,'linewidth',lw,'markersize',msize,'Marker','o','color','k','markerfacecolor','k','parent',axes1)
annotation(figcompare,'textbox',...
    [0.746 0.111 0.3 0.1],...
    'Color','k',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','left',...
    'String','planar geometry',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none');
plot(11.4,1.9e8,'linewidth',lw,'markersize',msize,'Marker','^','color','k','markerfacecolor','none','parent',axes1)
annotation(figcompare,'textbox',...
    [0.746 0.797 0.3 0.1],...
    'Color','k',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','left',...
    'String','Channel bound',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none');
plot(11.4,8.0e7,'linewidth',lw,'markersize',msize,'Marker','s','color','k','markerfacecolor','none','parent',axes1)
annotation(figcompare,'textbox',...
    [0.746 0.744 0.6 0.1],...
    'Color','k',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','left',...
    'String','Analyticity bound',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none');


% *** material x-axis labels
annotation(figcompare,'textbox',...
    [0.732 0.021 0.3 0.1],...
    'Color',c2D,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','2D \newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.675 0.021 0.3 0.1],...
    'Color',cidealmetal,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Drude \newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.626 0.021 0.3 0.1],...
    'Color',cidealITO,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','ITO \newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.575 0.0143 0.3 0.1],...
    'Color',cMgF2,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','MgF_2 \newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.518 0.0143 0.3 0.1],...
    'Color',cAlO,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Al_2O_3 \newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.461 0.021 0.3 0.1],...
    'Color',cInP,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','n-InP\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(figcompare,'textbox',...
    [0.405 0.021 0.3 0.1],...
    'Color',cGaAs,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','n-GaAs\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(figcompare,'textbox',...
    [0.354 0.0143 0.3 0.1],...
    'Color',cSiO2,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','SiO_2\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.302 0.021 0.3 0.1],...
    'Color',cSiC,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','SiC\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.245 0.021 0.3 0.1],...
    'Color',ccBN,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','cBN\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.19 0.021 0.3 0.1],...
    'Color',cSi,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','n-Si\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.14 0.021 0.3 0.1],...
    'Color',cAl,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Al\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.089 0.021 0.3 0.1],...
    'Color',cAu,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Au\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');
annotation(figcompare,'textbox',...
    [0.034 0.025 0.3 0.1],...
    'Color',cAg,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Ag\newline',...
    'FontSize',fs-1,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% *** 2.5X and 200X
annotation(figcompare,'doublearrow',...
    [0.825 0.825], [0.456 0.546],...
    'Color','k','linewidth',lw-1.2);

annotation(figcompare,'textbox',...
    [0.128 0.457 0.4 0.1],...
    'Color',cbtkk,...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'String','Matrix oscillator bound: 1.1\times10^6 Wm^{-2}K^{-1}',...
    'FontSize',fs+4,...
    'FitBoxToText','off',...
    'EdgeColor','none', 'fontweight', 'bold' );
annotation(figcompare,'textbox',...
    [0.796 0.449 0.3 0.1],...
    'Color','k',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','left',...
    'String','5X',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none');

annotation(figcompare,'doublearrow',...
    [0.845 0.845], [0.456 0.765],...
    'Color','k','linewidth',lw-1.2);
annotation(figcompare,'textbox',...
    [0.847 0.69 0.3 0.1],...
    'Color','k',...
    'VerticalAlignment','middle',...
    'HorizontalAlignment','left',...
    'String','200X',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none');

box off
set(gcf,'renderer','painters')
print -depsc2 bound_compare_narrow.eps