clc
close all

E = readmatrix('fig3.txt');
Exsource = E(:,1);
Extip = E(:,2);
Eysource = E(:,3);
Eytip = E(:,4);

e0 = 8.8542e-12; % epsilon_0

cgrey = [1,1,1].*0.65;
cred = [0.7695, 0, 0];
lw = 2.4; fs = 25; ms = '^'; msize = 12; mlw = 2;

figtrend = figure;
set(gcf,'color','w');
axes1 = axes('Parent',figtrend);
set(axes1,'fontsize',fs')
hold(axes1,'on');
set(axes1,'FontSize',fs,'XMinorTick','off','XScale','linear','YMinorTick','off',...
    'YScale','linear','position',[0.11 0.15 0.775 0.8],'TickDir','out');
set(gcf,'position',[10,300,900,570]);
set(gca,'fontsize',fs)
hold on
plot((1:1:8)./8,Eytip.*e0,'color',cgrey,'linewidth',lw,'marker','|','markersize',msize,'displayname','Escat at tip')
plot((1:1:8)./8,Eysource.*e0,'color',cred,'linewidth',lw,'marker','|','markersize',msize,'displayname','Escat at source')

plot((1:1:8)./8,Extip.*e0,'color',cgrey,'linewidth',lw,'marker','s','markersize',msize,'displayname','Escat at tip')
plot((1:1:8)./8,Exsource.*e0,'color',cred,'linewidth',lw,'marker','s','markersize',msize,'displayname','Escat at source')

xlabel('Conducting wedge inner angle, \beta (\pi)','fontsize',fs+4,'fontname','Helvetica','interpreter','tex')
ylabel('Scattered dipole field, E_{scat}','interpreter','tex','fontsize',fs+4)
xlim([0.1 1])
xticks(linspace(1,8,8)./8)

annotation('doublearrow',[.6 .6],[.86 .805],...
    'Color',cgrey,...
    'linewidth',lw-0.6)
annotation(figtrend,'textbox',...
    [0.605 0.76 0.3 0.1],...
    'Color',cgrey,...
    'String',', near tip',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none','interpreter','tex');

    annotation('doublearrow',[.295 .295],[.365 .42],...
    'Color',cred,...
    'linewidth',lw-0.6)
annotation(figtrend,'textbox',...
    [0.3 0.325 0.3 0.1],...
    'Color',cred,...
    'String',', at source',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none','interpreter','tex');

annotation('doublearrow',[.726 .763],[.48 .48],...
    'Color',cgrey,...
    'linewidth',lw-0.6)
annotation(figtrend,'textbox',...
    [0.763 0.412 0.3 0.1],...
    'Color',cgrey,...
    'String',', near tip',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none','interpreter','tex');

annotation('doublearrow',[.396 .433],[.24 .24],...
    'Color',cred,...
    'linewidth',lw-0.6)
annotation(figtrend,'textbox',...
    [0.433 0.17 0.3 0.1],...
    'Color',cred,...
    'String',', at source',...
    'FontSize',fs,...
    'FitBoxToText','off',...
    'EdgeColor','none','interpreter','tex');


set(gcf,'renderer','painters')
print -depsc2 monotonicity.eps